usuarios/applications/home/urls.py
from django.urls import path

from . import views

app_name = 'home_app'

urlpatterns = [
    path('', view=views.HomePage.as_view(), name='home'),
    path('prueba/', view=views.TemplatePruebaMixin.as_view(), name='prueba-mixin')
]

usuarios/applications/users/urls.py
from django.urls import path

# from usuarios.applications.home import views

from .views import (
    UserRegisterView, LoginUser, LogoutView, UpdatePasswordView,
    CodeVerificationView
)

app_name = 'users_app'

urlpatterns = [
    path('register/', view=UserRegisterView.as_view(), name='register-user'),
    path('login/', view=LoginUser.as_view(), name='login'),
    path('logout/', view=LogoutView.as_view(), name='logout'),
    path('update/', view=UpdatePasswordView.as_view(), name='update-password'),
    path('verificated/<pk>/', view=CodeVerificationView.as_view(), name='verificated'),
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls'))
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/home/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.views.generic import TemplateView


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:login')


class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.now()
        return context
    
    
class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = 'home/prueba.html'

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenidos</title>
</head>

<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenidos: {{user}}</h3>
    <ul>
        <li><a href="{% url 'users_app:logout' %}">Cerrar session</a></li>
        <li><a href="{% url 'users_app:update-password' %}">Actualizar Datos</a></li>
    </ul>
</body>

</html>

usuarios/templates/home/prueba.html
<h2>Prueba mixin</h2>
<p>
    {{fecha}}
</p>